### ISSUE TITLE
Should minutes be seconds?

### ISSUE THREAD

**Issue by re222dv** [IOT-DSA/docs#1]
In <https://github.com/IOT-DSA/docs/wiki/Protocol%20Communication> you say:

>when in websocket mode, both client and server need to make sure a message is sent to other side at least once every 60 minutes, (because of network latency can cause message delay on other side, 30 ~ 45 seconds is suggested interval for a minimal interval)
>
>if no message is received in 60 seconds, websocket should be considered disconnected and a re-connection is needed

The first paragraph should probably state "once every 60 _**seconds**_"

**Comment by kaendfinger** [comment]
cc @rinick @samrg472

**Comment by rinick** [comment]
fixed

**Comment by kaendfinger** [comment]
@re222dv Thanks for the help :)
