### ISSUE TITLE
users.sh missing file

### ISSUE THREAD

**Issue by antowan** [IOT-DSA/docs#4]
In the last instruction in the docker file you wrote :

> RUN bin/users.sh add -u myuser -p mypassword

but when I log to the server and do a ls in /app/bin there is no users.sh file just users.dart file

Thanks.

**Comment by kaendfinger** [comment]
@antowan Thanks for pointing this out. I will fix this.

**Comment by kaendfinger** [comment]
@antowan Fixed :)

**Comment by antowan** [comment]
Thanks!
Just to be sure I rebuilt my custom docker image file but the bin/users.sh file is still missing.
Could you tell if the base image iotdsa/dglux-server is rebuilt with this change ?

**Comment by kaendfinger** [comment]
@antowan Sorry, I was unclear. The shell scripts are non-existent by design. I have instead updated the docs to give you the correct line to use.

Use this instead:
```docker
RUN dart bin/users.dart add -u myuser -p mypassword
```

**Comment by antowan** [comment]
@kaendfinger Thank you ! Fixed.
