### ISSUE TITLE
 Custom settings are overidden when server start

### ISSUE THREAD

**Issue by antowan** [IOT-DSA/docs#5]
I tried to include in my custom image the following instructions 

> WORKDIR /app
> ADD conf/server.json .
> ADD conf/certs certs

But when the server is launched those files are overridden.
I tried to put in /data but when the volume is mounted same problem appears.

**Comment by kaendfinger** [comment]
Ok, I will try to test this and see what is wrong. This should definitely never happen.

**Comment by antowan** [comment]
I rebuilt the image from google/dart:latest but same problem.
It looks like when the server startup that the server.json file is automatically modified.
So in that case docker detect a change a pull the file in /data and that override my settings.
Is there any way to configure the /app/bin/server_watcher.dart to prevent that ?

**Comment by kaendfinger** [comment]
@antowan I am finally looking at this issue.

**Comment by seancostigan** [comment]
I know this is an old issue, but are there any updates on this? I am having the same problem with the server.json file being overwritten. I have followed the instructions on the [Wiki](https://github.com/IOT-DSA/docs/wiki/Docker)

**Comment by seancostigan** [comment]
Not sure what I was doing wrong previously, but this is working as expected for me now. The custom server.json is used and is not overwritten.
